test semgreb

diff --git a/.github/workflows/semgrep.yml b/.github/workflows/semgrep.yml
--- a/.github/workflows/semgrep.yml
+++ b/.github/workflows/semgrep.yml
@@ -6,7 +6,7 @@ on:
   schedule:
   # random HH:MM to avoid a load spike on GitHub Actions at 00:00
   - cron: 28 2 * * *
-name: Semgrep
+name: Semgrep Analysis
 jobs:
   semgrep:
     name: semgrep/ci
@@ -17,4 +17,23 @@ jobs:
       image: returntocorp/semgrep
     steps:
     - uses: actions/checkout@v3
-    - run: semgrep ci
+
+    - name: Run Semgrep
+      run: semgrep ci --json > semgrep_results.json
+      
+    - name: Analyze Semgrep results
+        id: analyze
+        run: |
+          # Load the JSON results
+          results=$(cat semgrep_results.json)
+
+          # Count the number of findings
+          count=$(echo $results | jq '.results | length')
+
+          # Fail if any findings are present
+          if [ "$count" -gt 0 ]; then
+            echo "There are $count Semgrep findings. Failing the build."
+            exit 1
+          else
+            echo "No Semgrep findings. Success."
+          fi
